project_metadata:
  package: GDGUkraine

global:
  engine.url_for.on: true
  engine.logging.on: true
  engine.sqlalchemy.on: true
  engine.oauth.on: true
  google_oauth:
    id: <google_app_id>.apps.googleusercontent.com
    secret: <google_app_secret>
    scope:
        - https://www.googleapis.com/auth/userinfo.email
        - https://www.googleapis.com/auth/userinfo.profile
        # Send an email message:
        - https://www.googleapis.com/auth/gmail.compose
        # Create a new file on Google Drive
        - https://www.googleapis.com/auth/drive.file
  #tools.trailing_slash.on: false
  base_app_url: http://localhost:8080
  alembic:
    # path to migration scripts
    script_location: src/db
    # template used to generate migration files
    # file_template: %%(rev)s_%%(slug)s

    # max length of characters to apply to the
    # "slug" field
    #truncate_slug_length: 40

    # set to 'true' to run the environment during
    # the 'revision' command, regardless of autogenerate
    # revision_environment: false

    # set to 'true' to allow .pyc and .pyo files without
    # a source .py file to be detected as revisions in the
    # versions/ directory
    # sourceless: false

    # version location specification; this defaults
    # to db/versions.  When using multiple version
    # directories, initial revisions must be specified with --version-path
    # version_locations: %(here)s/bar %(here)s/bat db/versions

    # the output encoding used when revision files
    # are written from script.py.mako
    # output_encoding: utf-8
    sqlalchemy.url: &db_url !FirstOf
      - !EnvVar DATABASE_URL
      - mysql+mysqlconnector://dbuser:dbpwd@/dbname?unix_socket=/var/run/mysqld/mysqld.sock
  alembic.exclude:
    tables:
      - gdg_blog_posts_view  # exclude view, aggregating posts from all GDGs
      # Exclude Wordpress-specific tables:
      - wp_blog_versions
      - wp_blogs
      - wp_commentmeta
      - wp_comments
      - wp_links
      - wp_openid_identities
      - wp_options
      - wp_postmeta
      - wp_posts
      - wp_posts_dup
      - wp_registration_log
      - wp_signups
      - wp_site
      - wp_sitemeta
      - wp_term_relationships
      - wp_term_taxonomy
      - wp_terms
      - wp_usermeta
      - wp_users
    indexes:
      - ix_gdg_admins_email
      - ix_gdg_admins_filter_place
      - ix_gdg_admins_googler_id
      - googler_id_UNIQUE
      - id_UNIQUE
      - code_UNIQUE
      - ix_gdg_participants_company
      - ix_gdg_participants_email
      - ix_gdg_participants_gplus
      - ix_gdg_participants_hometown
      - ix_gdg_participants_local_gdg_id
      - ix_gdg_participants_nickname
      - ix_gdg_participants_phone
      - ix_gdg_participants_position
      - email_UNIQUE
      - uid_UNIQUE
    foreign_keys:
      - gdg_participants_ibfk_1
    unique_keys:
      - unique_participation

controllers:
  '':
    controller: !!python/name:GDGUkraine.controller.Root
    /:
      tools.orm_session.on: true
      tools.sessions.on: true
      tools.staticdir.root: static
      tools.staticfile.root: static
    /css:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: css
    /js:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: js
    /img:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: img
    /libs:  # Path for third-party libs, bower_components etc.
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: libs
    /admin:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: templates/admin/admin.html
    /templates:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: templates
    /favicon.ico:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: favicon.ico
    /google55b33f78b4c8d4c6.html:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: google55b33f78b4c8d4c6.html
  /api:
    controller: !!python/name:GDGUkraine.rest_controller.rest_api
    /:
      request.dispatch: !!python/name:GDGUkraine.rest_controller.rest_api
      request.error_response: !!python/name:GDGUkraine.errors.unexpected_json_error_handler
      error_page.default: !!python/name:GDGUkraine.errors.generic_json_error_handler
      tools.orm_session.on: true
      tools.sessions.on: true
  /events:
    controller: !!python/name:GDGUkraine.events_controller.events
    /:
      request.dispatch: !!python/name:GDGUkraine.events_controller.events
      tools.orm_session.on: true
      tools.sessions.on: true

sqlalchemy_engine:
  url: *db_url
  #pool_recycle: 3600
  pool_recycle: 60

jinja2:
  loader: !!python/object:jinja2.loaders.FileSystemLoader
          encoding: utf-8
          searchpath: [src/GDGUkraine/templates]
  bytecode_cache: !!python/object:jinja2.bccache.FileSystemBytecodeCache {directory: .cache,
                                                                          pattern: __jinja2_%s.cache}
  auto_reload: true
  use_webassets: true
  globals:
    is_admin: !!python/name:GDGUkraine.lib.utils.auth.is_admin
    url_for: !!python/name:GDGUkraine.lib.utils.url.url_for
    url_for_class: !!python/name:GDGUkraine.lib.utils.url.url_for_class
    url_for_routes: !!python/name:GDGUkraine.lib.utils.url.url_for_routes
    url_for_cp: !!python/name:GDGUkraine.lib.utils.url.url_for_cp
    url_for_static: !!python/name:GDGUkraine.lib.utils.url.url_for_static
